apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: basic-cluster
  region: us-east-2

managedNodeGroups:
  - name: ng-1
    instanceType: t2.micro
    minSize: 1
    desiredCapacity: 2
    maxSize: 3